# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - Dockerfile
      - DESIGN2.md
      - runtests.sh
      - build.sh

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DockerInstaller@0

  - script: docker pull mysql
    displayName: 'pull mysql image'

  - script: docker run -p -e MYSQL_ROOT_PASSWORD=1qazZAQ! -d mysql
    displayName: 'start mysql'

  - script: docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=1qazZAQ!' -p -d mcr.microsoft.com/mssql/server:2017-latest
    displayName: 'start sqlserver'

  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.100'
